import type { Metadata } from "next";
import ReduxProvider from "./redux-provider";

import { geologica } from "@/app/ui/fonts";
import "@/app/ui/globals.css";
import "../../public/css/weather-icons/weather-icons.min.css";
import "../../public/css/weather-icons/weather-icons-wind.min.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${geologica.className} antialiased`}>
      <body>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
